version: '3.1'

services:
  db-argos:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: argos
      POSTGRES_USER: postgres
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
