name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- run: 
    - run: npm install
    - run: npm test
      env:
        CI: true
        NODE_ENV: test
        APP_SECRET: test
        DB_DIALECT: postgres
        DB_HOST: localhost
        DB_PORT: ${{ job.services.postgres.ports[5432] }}
        DB_USER: postgres
        DB_PASS: postgres
        DB_NAME: postgres